version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
      - OLLAMA_NO_CLOUD=${OLLAMA_NO_CLOUD}

    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull ${OLLAMA_MODEL} &&
        wait
      "

  whisper:
    image: fedirz/faster-whisper-server:latest-cuda
    container_name: whisper
    restart: unless-stopped
    runtime: nvidia
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - WHISPER_DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    volumes:
      - whisper_data:/root/.cache/huggingface

  webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "${WEBUI_PORT}:8080"
    depends_on:
      - ollama
      - whisper
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_AUTH=${WEBUI_AUTH}
      - WEBUI_NAME=${WEBUI_NAME}
      - AUDIO_STT_ENGINE=openai
      - AUDIO_STT_OPENAI_API_BASE_URL=http://whisper:8000/v1
      - AUDIO_STT_OPENAI_API_KEY=cant-be-empty
      - AUDIO_STT_MODEL=base
      - ENABLE_AUDIO_TRANSCRIPTION=true
    volumes:
      - webui_data:/app/backend/data # host on windows is C:\*whatever*\ProgramData\Docker\volumes\webui_data\_data
      # stmpfs   /mnt/whateveronhost   tmpfs   defaults,size=2G   0 0
      # sudo mount -t tmpfs -o size=2G tmpfs /mnt/whateveronhost

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - webui
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TOKEN}

volumes:
  ollama_data:
  webui_data:
  whisper_data: